pub mod backend;
pub mod endpoint;
pub mod queue;
pub mod throughput;

use std::sync::Arc;

use prometheus::{CounterVec, GaugeVec, HistogramOpts, HistogramVec, Opts, Registry};

/// Central metrics collector holding all Prometheus gauges, counters,
/// and histograms for the tinyllb.
///
/// Stored as `Arc<Metrics>` inside `AppState` so every request handler
/// can access the same registry.  Later issues (06 backpressure, 08 flows)
/// only register new collectors into this shared registry.
// @lat: [[metrics#Metrics Registry]]
pub struct Metrics {
    pub registry: Registry,

    // -- Queue family --
    /// Per-flow queue depth gauge.  Labeled by `flow_id`.
    /// Ephemeral flows aggregate to the label value `"ephemeral"`.
    pub queue_depth: GaugeVec,
    pub queue_wait_seconds: prometheus::Histogram,
    pub active_flows: prometheus::Gauge,

    // -- Throughput family --
    pub tokens_generated_total: prometheus::Counter,
    pub tokens_per_second: prometheus::Gauge,

    // -- Backend family --
    pub requests_active: prometheus::Gauge,
    pub errors_total: prometheus::IntCounter,

    // -- Backpressure family --
    pub backpressure_rejections_total: CounterVec,

    // -- Scheduling family (DRR) --
    /// Per-flow credit gauge for DRR.  Labeled by `flow_id`.
    pub flow_credit: GaugeVec,

    // -- Starvation protection --
    /// Observed starvation wait time per flow at force-admit (seconds).
    pub flow_starvation_seconds: GaugeVec,
    /// Total number of force-admit events due to starvation protection.
    pub starvation_force_admits_total: prometheus::IntCounter,

    // -- Request lifecycle events (PRD §6.8) --
    /// Lifecycle events: request_started, token_received, request_completed, request_cancelled.
    pub request_events_total: CounterVec,

    // -- KV cache family (PRD §6.3) --
    /// KV cache usage percentage reported by vLLM backend.
    pub vllm_kv_cache_usage: prometheus::Gauge,
    /// KV cache free percentage reported by vLLM backend.
    pub vllm_kv_cache_free: prometheus::Gauge,
    /// 1 while the inference watchdog considers the backend deadlocked.
    pub llm_backend_stalled: prometheus::Gauge,
    /// Backend inference stalls detected by the watchdog.
    pub backend_stall_events_total: prometheus::Counter,
    /// KV admission decisions: accept, delay, reject.
    pub kv_admission_decisions_total: CounterVec,

    // -- Priority heuristic family (plan 004) --
    /// Per-flow numeric priority value (100/50/10). Labeled by `flow_id`.
    pub flow_priority_class: GaugeVec,
    /// Source of the priority value: header, admin, auto. Labeled by `flow_id`, `source`.
    pub flow_priority_source_total: CounterVec,
    /// Observed inter-request gap per flow (seconds). Labeled by `flow_id`.
    pub flow_inter_request_seconds: HistogramVec,
    /// Per-flow cadence state machine state. Labeled by `flow_id`.
    pub flow_cadence_state: GaugeVec,
    // -- Premature stop retry family --
    pub premature_stop_detected_total: prometheus::Counter,
    pub premature_stop_retries_total: prometheus::Counter,
    pub premature_stop_exhausted_total: prometheus::Counter,

    // -- Transient backend retry family --
    pub backend_retries_total: prometheus::Counter,
    pub backend_retry_exhausted_total: prometheus::Counter,
}

impl Default for Metrics {
    fn default() -> Self {
        Self::new()
    }
}

impl Metrics {
    /// Create a new `Metrics` instance with all collectors registered in a
    /// freshly-created `Registry`.
    pub fn new() -> Self {
        let registry = Registry::new();

        let queue_depth = GaugeVec::new(
            Opts::new(
                "llm_queue_depth",
                "Current number of requests waiting in the queue",
            ),
            &["flow_id"],
        )
        .expect("llm_queue_depth should be creatable");

        let queue_wait_seconds = prometheus::Histogram::with_opts(
            HistogramOpts::new(
                "llm_queue_wait_seconds",
                "Time a request spends waiting in the queue",
            )
            .buckets(vec![0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0]),
        )
        .expect("llm_queue_wait_seconds should be creatable");

        let active_flows =
            prometheus::Gauge::new("llm_active_flows", "Number of currently active flows")
                .expect("llm_active_flows should be creatable");

        let tokens_generated_total = prometheus::Counter::new(
            "llm_tokens_generated_total",
            "Total number of tokens generated by the backend",
        )
        .expect("llm_tokens_generated_total should be creatable");

        let tokens_per_second = prometheus::Gauge::new(
            "llm_tokens_per_second",
            "Approximate tokens generated per second (updated every second)",
        )
        .expect("llm_tokens_per_second should be creatable");

        let requests_active = prometheus::Gauge::new(
            "vllm_requests_active",
            "Number of in-flight requests to the vLLM backend",
        )
        .expect("vllm_requests_active should be creatable");

        let errors_total = prometheus::IntCounter::new(
            "vllm_errors_total",
            "Total number of backend errors (5xx responses and network errors)",
        )
        .expect("vllm_errors_total should be creatable");

        let backpressure_rejections_total = CounterVec::new(
            Opts::new(
                "llm_backpressure_rejections_total",
                "Total number of requests rejected by backpressure",
            ),
            &["mode"],
        )
        .expect("llm_backpressure_rejections_total should be creatable");

        let flow_credit = GaugeVec::new(
            Opts::new(
                "llm_flow_credit",
                "Current DRR credit per flow (integer units)",
            ),
            &["flow_id"],
        )
        .expect("llm_flow_credit should be creatable");

        let flow_starvation_seconds = GaugeVec::new(
            Opts::new(
                "llm_flow_starvation_seconds",
                "Observed starvation wait time per flow at force-admit (seconds)",
            ),
            &["flow_id"],
        )
        .expect("llm_flow_starvation_seconds should be creatable");

        let starvation_force_admits_total = prometheus::IntCounter::new(
            "llm_starvation_force_admits_total",
            "Total number of force-admit events due to starvation protection",
        )
        .expect("llm_starvation_force_admits_total should be creatable");

        let request_events_total = CounterVec::new(
            Opts::new(
                "llm_request_events_total",
                "Lifecycle events: request_started, token_received, request_completed, request_cancelled",
            ),
            &["event"],
        )
        .expect("llm_request_events_total should be creatable");

        let vllm_kv_cache_usage = prometheus::Gauge::new(
            "vllm_kv_cache_usage",
            "KV cache usage percentage reported by vLLM backend",
        )
        .expect("vllm_kv_cache_usage should be creatable");

        let vllm_kv_cache_free = prometheus::Gauge::new(
            "vllm_kv_cache_free",
            "KV cache free percentage reported by vLLM backend",
        )
        .expect("vllm_kv_cache_free should be creatable");

        let llm_backend_stalled = prometheus::Gauge::new(
            "llm_backend_stalled",
            "1 while the inference watchdog considers the backend deadlocked (busy, no token progress)",
        )
        .expect("llm_backend_stalled should be creatable");

        let backend_stall_events_total = prometheus::Counter::new(
            "tinyllb_backend_stall_events_total",
            "Backend inference stalls detected by the watchdog",
        )
        .expect("backend_stall_events_total should be creatable");

        let kv_admission_decisions_total = CounterVec::new(
            Opts::new(
                "llm_kv_admission_decisions_total",
                "KV admission decisions: accept, delay, reject",
            ),
            &["decision"],
        )
        .expect("llm_kv_admission_decisions_total should be creatable");

        // -- Priority heuristic family (plan 004) --
        let flow_priority_class = GaugeVec::new(
            Opts::new(
                "llm_flow_priority_class",
                "Per-flow numeric priority value (100/50/10)",
            ),
            &["flow_id"],
        )
        .expect("llm_flow_priority_class should be creatable");

        let flow_priority_source_total = CounterVec::new(
            Opts::new(
                "llm_flow_priority_source_total",
                "Source of the priority value: header, admin, auto",
            ),
            &["flow_id", "source"],
        )
        .expect("llm_flow_priority_source_total should be creatable");

        let flow_inter_request_seconds = HistogramVec::new(
            HistogramOpts::new(
                "llm_flow_inter_request_seconds",
                "Observed inter-request gap per flow (seconds)",
            )
            .buckets(vec![0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0]),
            &["flow_id"],
        )
        .expect("llm_flow_inter_request_seconds should be creatable");

        let flow_cadence_state = GaugeVec::new(
            Opts::new(
                "llm_flow_cadence_state",
                "Per-flow cadence state machine state (0=cold, 1=interactive, 2=agentic_suspected, 3=agentic_confirmed)",
            ),
            &["flow_id"],
        )
        .expect("llm_flow_cadence_state should be creatable");
        // -- Premature stop retry family --
        let premature_stop_detected_total = prometheus::Counter::new(
            "tinyllb_premature_stop_detected_total",
            "Premature stops detected (one per failed attempt)",
        )
        .expect("premature_stop_detected_total should be creatable");

        let premature_stop_retries_total = prometheus::Counter::new(
            "tinyllb_premature_stop_retries_total",
            "Retry requests issued after a premature stop",
        )
        .expect("premature_stop_retries_total should be creatable");

        let premature_stop_exhausted_total = prometheus::Counter::new(
            "tinyllb_premature_stop_exhausted_total",
            "Degenerate turns forwarded after all retries exhausted",
        )
        .expect("premature_stop_exhausted_total should be creatable");

        // -- Transient backend retry family --
        let backend_retries_total = prometheus::Counter::new(
            "tinyllb_backend_retries_total",
            "Proxy-side re-forwards of transient backend errors (llama.cpp context-exceed where prompt fits slot capacity, or network errors from backend restart, or mid-stream KV exhaustion before any content forwarded)",
        )
        .expect("tinyllb_backend_retries_total should be creatable");

        let backend_retry_exhausted_total = prometheus::Counter::new(
            "tinyllb_backend_retry_exhausted_total",
            "Transient backend retries exhausted (last error response forwarded to client)",
        )
        .expect("tinyllb_backend_retry_exhausted_total should be creatable");

        // Register all collectors with the registry.
        registry
            .register(Box::new(queue_depth.clone()))
            .expect("llm_queue_depth registration should succeed");
        registry
            .register(Box::new(queue_wait_seconds.clone()))
            .expect("llm_queue_wait_seconds registration should succeed");
        registry
            .register(Box::new(active_flows.clone()))
            .expect("llm_active_flows registration should succeed");
        registry
            .register(Box::new(tokens_generated_total.clone()))
            .expect("llm_tokens_generated_total registration should succeed");
        registry
            .register(Box::new(tokens_per_second.clone()))
            .expect("llm_tokens_per_second registration should succeed");
        registry
            .register(Box::new(requests_active.clone()))
            .expect("vllm_requests_active registration should succeed");
        registry
            .register(Box::new(errors_total.clone()))
            .expect("vllm_errors_total registration should succeed");
        registry
            .register(Box::new(backpressure_rejections_total.clone()))
            .expect("llm_backpressure_rejections_total registration should succeed");
        registry
            .register(Box::new(flow_credit.clone()))
            .expect("llm_flow_credit registration should succeed");
        registry
            .register(Box::new(flow_starvation_seconds.clone()))
            .expect("llm_flow_starvation_seconds registration should succeed");
        registry
            .register(Box::new(starvation_force_admits_total.clone()))
            .expect("llm_starvation_force_admits_total registration should succeed");
        registry
            .register(Box::new(request_events_total.clone()))
            .expect("llm_request_events_total registration should succeed");
        registry
            .register(Box::new(vllm_kv_cache_usage.clone()))
            .expect("vllm_kv_cache_usage registration should succeed");
        registry
            .register(Box::new(vllm_kv_cache_free.clone()))
            .expect("vllm_kv_cache_free registration should succeed");
        registry
            .register(Box::new(llm_backend_stalled.clone()))
            .expect("llm_backend_stalled registration should succeed");
        registry
            .register(Box::new(backend_stall_events_total.clone()))
            .expect("backend_stall_events_total registration should succeed");
        registry
            .register(Box::new(kv_admission_decisions_total.clone()))
            .expect("llm_kv_admission_decisions_total registration should succeed");

        // Register priority heuristic metrics.
        registry
            .register(Box::new(flow_priority_class.clone()))
            .expect("llm_flow_priority_class registration should succeed");
        registry
            .register(Box::new(flow_priority_source_total.clone()))
            .expect("llm_flow_priority_source_total registration should succeed");
        registry
            .register(Box::new(flow_inter_request_seconds.clone()))
            .expect("llm_flow_inter_request_seconds registration should succeed");
        registry
            .register(Box::new(flow_cadence_state.clone()))
            .expect("llm_flow_cadence_state registration should succeed");
        // Register premature stop retry metrics.
        registry
            .register(Box::new(premature_stop_detected_total.clone()))
            .expect("premature_stop_detected_total registration should succeed");
        registry
            .register(Box::new(premature_stop_retries_total.clone()))
            .expect("premature_stop_retries_total registration should succeed");
        registry
            .register(Box::new(premature_stop_exhausted_total.clone()))
            .expect("premature_stop_exhausted_total registration should succeed");
        // Register transient backend retry metrics.
        registry
            .register(Box::new(backend_retries_total.clone()))
            .expect("backend_retries_total registration should succeed");
        registry
            .register(Box::new(backend_retry_exhausted_total.clone()))
            .expect("backend_retry_exhausted_total registration should succeed");


        Metrics {
            registry,
            queue_depth,
            queue_wait_seconds,
            active_flows,
            tokens_generated_total,
            tokens_per_second,
            requests_active,
            errors_total,
            backpressure_rejections_total,
            flow_credit,
            flow_starvation_seconds,
            starvation_force_admits_total,
            request_events_total,
            vllm_kv_cache_usage,
            vllm_kv_cache_free,
            llm_backend_stalled,
            backend_stall_events_total,
            kv_admission_decisions_total,
            flow_priority_class,
            flow_priority_source_total,
            flow_inter_request_seconds,
            flow_cadence_state,
            premature_stop_detected_total,
            premature_stop_retries_total,
            premature_stop_exhausted_total,
            backend_retries_total,
            backend_retry_exhausted_total,
        }
    }
}

/// Return a handle suitable for sharing across async tasks.
pub fn create_metrics() -> Arc<Metrics> {
    Arc::new(Metrics::new())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_priority_metrics_registered() {
        let metrics = Metrics::new();
        // Instantiate one series per collector so they show up in gather().
        metrics.flow_priority_class.with_label_values(&["test"]).set(50.0);
        metrics.flow_priority_source_total.with_label_values(&["test", "header"]).inc();
        metrics.flow_inter_request_seconds.with_label_values(&["test"]).observe(1.0);

        let gathers = metrics.registry.gather();
        let names: Vec<&str> = gathers.iter().map(|m| m.name()).collect();
        assert!(
            names.contains(&"llm_flow_priority_class"),
            "flow_priority_class should be registered"
        );
        assert!(
            names.contains(&"llm_flow_priority_source_total"),
            "flow_priority_source_total should be registered"
        );
        assert!(
            names.contains(&"llm_flow_inter_request_seconds"),
            "flow_inter_request_seconds should be registered"
        );
    }
}
