pub mod backend;
pub mod endpoint;
pub mod queue;
pub mod throughput;

use std::sync::Arc;

use prometheus::{CounterVec, GaugeVec, HistogramOpts, Opts, Registry};

/// Central metrics collector holding all Prometheus gauges, counters,
/// and histograms for the LLM QDisc Proxy.
///
/// Stored as `Arc<Metrics>` inside `AppState` so every request handler
/// can access the same registry.  Later issues (05 FIFO, 06 backpressure,
/// 08 flows) only register new collectors into this shared registry.
pub struct Metrics {
    pub registry: Registry,

    // -- Queue family --
    /// Per-flow queue depth gauge.  Labeled by `flow_id`.
    /// Ephemeral flows aggregate to the label value `"ephemeral"`.
    pub queue_depth: GaugeVec,
    pub queue_wait_seconds: prometheus::Histogram,
    pub active_flows: prometheus::Gauge,

    // -- Throughput family --
    pub tokens_generated_total: prometheus::Counter,
    pub tokens_per_second: prometheus::Gauge,

    // -- Backend family --
    pub requests_active: prometheus::Gauge,
    pub errors_total: prometheus::IntCounter,

    // -- Backpressure family --
    pub backpressure_rejections_total: CounterVec,
}

impl Default for Metrics {
    fn default() -> Self {
        Self::new()
    }
}

impl Metrics {
    /// Create a new `Metrics` instance with all collectors registered in a
    /// freshly-created `Registry`.
    pub fn new() -> Self {
        let registry = Registry::new();

        let queue_depth = GaugeVec::new(
            Opts::new(
                "llm_queue_depth",
                "Current number of requests waiting in the queue",
            ),
            &["flow_id"],
        )
        .expect("llm_queue_depth should be creatable");

        let queue_wait_seconds = prometheus::Histogram::with_opts(
            HistogramOpts::new(
                "llm_queue_wait_seconds",
                "Time a request spends waiting in the queue",
            )
            .buckets(vec![0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0]),
        )
        .expect("llm_queue_wait_seconds should be creatable");

        let active_flows =
            prometheus::Gauge::new("llm_active_flows", "Number of currently active flows")
                .expect("llm_active_flows should be creatable");

        let tokens_generated_total = prometheus::Counter::new(
            "llm_tokens_generated_total",
            "Total number of tokens generated by the backend",
        )
        .expect("llm_tokens_generated_total should be creatable");

        let tokens_per_second = prometheus::Gauge::new(
            "llm_tokens_per_second",
            "Approximate tokens generated per second (updated every second)",
        )
        .expect("llm_tokens_per_second should be creatable");

        let requests_active = prometheus::Gauge::new(
            "vllm_requests_active",
            "Number of in-flight requests to the vLLM backend",
        )
        .expect("vllm_requests_active should be creatable");

        let errors_total = prometheus::IntCounter::new(
            "vllm_errors_total",
            "Total number of backend errors (5xx responses and network errors)",
        )
        .expect("vllm_errors_total should be creatable");

        let backpressure_rejections_total = CounterVec::new(
            Opts::new(
                "llm_backpressure_rejections_total",
                "Total number of requests rejected by backpressure",
            ),
            &["mode"],
        )
        .expect("llm_backpressure_rejections_total should be creatable");

        // Register all collectors with the registry.
        registry
            .register(Box::new(queue_depth.clone()))
            .expect("llm_queue_depth registration should succeed");
        registry
            .register(Box::new(queue_wait_seconds.clone()))
            .expect("llm_queue_wait_seconds registration should succeed");
        registry
            .register(Box::new(active_flows.clone()))
            .expect("llm_active_flows registration should succeed");
        registry
            .register(Box::new(tokens_generated_total.clone()))
            .expect("llm_tokens_generated_total registration should succeed");
        registry
            .register(Box::new(tokens_per_second.clone()))
            .expect("llm_tokens_per_second registration should succeed");
        registry
            .register(Box::new(requests_active.clone()))
            .expect("vllm_requests_active registration should succeed");
        registry
            .register(Box::new(errors_total.clone()))
            .expect("vllm_errors_total registration should succeed");
        registry
            .register(Box::new(backpressure_rejections_total.clone()))
            .expect("llm_backpressure_rejections_total registration should succeed");

        Metrics {
            registry,
            queue_depth,
            queue_wait_seconds,
            active_flows,
            tokens_generated_total,
            tokens_per_second,
            requests_active,
            errors_total,
            backpressure_rejections_total,
        }
    }
}

/// Return a handle suitable for sharing across async tasks.
pub fn create_metrics() -> Arc<Metrics> {
    Arc::new(Metrics::new())
}
